### ISSUE TITLE
0.3.3: sticky bug

### ISSUE THREAD

**Issue by J--** [kimabrandt/yarip#1]
Visit a page to edit (whether or not RIPs exist for the page)

1 click YARIP addon bar triangle
2 before clicking anything reload current page [click circular arrow near location bar]
3a try clicking anything with YARIP [as it is still in active triangle mode]
3b or try toggling status of YAPIP
4 no joy

It seems exiting- and restarting the browser [profile] is necessary to again wield YARIP

**Comment by kimabrandt** [comment]
Fixed some TypeError `can't access dead object' in kimabrandt@ecbdd089581c6ed00ff0cbc68b4352cdb4d3ebd2
